### ISSUE TITLE
Use generated frontend API client

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [dinnerdonebetter/dinnerdonebetter#838]
- [x] JWT generation login route (#840)
- [x] accept JWT instead of cookie for OAuth2 tokens (#841)
- [x] adapt frontend to use OAuth2 client ID and token (#842)
- [x] adapt frontend to use OAuth2 token with generated client (#843)
- [x] dump cookie support entirely (#846)
